---
# tasks file for system
- name: Show CPU count
  ansible.builtin.debug:
    var:
      ansible_hostname,
      ansible_facts.processor_count,
      ansible_facts.memtotal_mb
  tags:
  - system-all
  - system-info

- name: Set hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined
  tags:
  - system-all
  - system-set-hostname

- name: Get hostname
  debug:
    msg: "{{ ansible_hostname }}"
  when: hostname is defined
  tags:
  - system-all
  - system-set-hostname


- name: Stop iptables
  service: name=iptables state=stopped
  when:
  - iptables_status is defined
  - not iptables_status
  tags:
  - system-all
  - system-iptables-action

- name: Disbale iptable on boot
  service: name=iptables enabled=no
  when:
    - iptables_status is defined
    - not iptables_status
  tags:
    - system-all
    - system-iptables-action

- name: change sysctl options
  sysctl: name={{ item.name }} value={{ item.value }} sysctl_set=yes state=present reload=yes
  ignore_errors: true
  with_items:
    - { "name": "vm.swappiness", "value": 1 }
    - { "name": "net.ipv4.tcp_tw_reuse", "value": "1" }
    - { "name": "net.ipv4.tcp_fin_timeout", "value": "10" }
    - { "name": "net.core.somaxconn", "value": "4096" }
    - { "name": "net.ipv4.tcp_max_syn_backlog", "value": "8192" }
    - { "name": "net.ipv4.ip_local_port_range", "value": "10000 65000" }
  tags:
    - system-all
    - system-change-sysctl

- name: Add custom PS1 to root's .bashrc
  lineinfile:
    path: /root/.bashrc
    line: 'PS1="[\A$(date ''+%:::z'')\[\033[35m\] \u@\h\[\033[m\]:\w]# "'
    state: present
    insertafter: EOF

- name: Add GREP_OPTIONS to root's .bashrc
  lineinfile:
    path: /root/.bashrc
    line: 'export GREP_OPTIONS=''--color=auto'''
    state: present
    insertafter: EOF

- name: Add GREP_COLOR to root's .bashrc
  lineinfile:
    path: /root/.bashrc
    line: 'export GREP_COLOR=''1;35'''
    state: present
    insertafter: EOF

- name: correct system limits
  pam_limits: domain=* limit_type=- limit_item={{ item.name }} value={{ item.value }}
  with_items:
    - { "name": "nofile", "value": "512000" }
    - { "name": "nproc", "value": "64000" }
  tags:
    - system-all
    - system-change-limits-conf

- name: Delete default 90-nproc.conf
  file:
    path: "/etc/security/limits.d/90-nproc.conf"
    state: absent
  tags:
    - system-all
    - system-change-limits-conf

- name: install base Packages
  apt:
    name:
    - "mc"
    - "iotop"
    - "iftop"
    - "wget"
    - "deltarpm"
    - "lsof"
    - "screen"
    - "finger"
    - "mlocate"
    - "ncdu"
    - "netcat"
    - "mtr"
    - "tcpdump"
    - "pigz"
    - "ngrep"
    - "net-tools"
    # lock_timeout: 360
    state: present
    update_cache: yes
  ignore_errors: yes
  tags:
    - system-all
    - system-rpm


