---
# Displays basic system information: hostname, CPU count, and total memory
- name: Show CPU count
  ansible.builtin.debug:
    var:
      ansible_hostname,
      ansible_facts.processor_count,
      ansible_facts.memtotal_mb
  tags:
  - system-all
  - system-info

# Sets the hostname according to the provided variable
- name: Set hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined
  tags:
  - system-all
  - system-set-hostname

# Sets the hostname according to the provided variable
- name: Get hostname
  debug:
    msg: "{{ ansible_hostname }}"
  when: hostname is defined
  tags:
  - system-all
  - system-set-hostname

# Stops the iptables service if iptables_status is set to false
- name: Stop iptables
  service: name=iptables state=stopped
  when:
  - iptables_status is defined
  - not iptables_status
  tags:
  - system-all
  - system-iptables-action

# Disables iptables autostart at system boot if iptables_status is set to false
- name: Disbale iptable on boot
  service: name=iptables enabled=no
  when:
    - iptables_status is defined
    - not iptables_status
  tags:
    - system-all
    - system-iptables-action

# Configures optimal kernel parameters for server performance:
# - Reduces swap usage
# - Improves TCP connection handling
# - Increases connection queue sizes
# - Expands local port range
- name: change sysctl options
  sysctl: name={{ item.name }} value={{ item.value }} sysctl_set=yes state=present reload=yes
  ignore_errors: true
  with_items:
    - { "name": "vm.swappiness", "value": 1 }
    - { "name": "net.ipv4.tcp_tw_reuse", "value": "1" }
    - { "name": "net.ipv4.tcp_fin_timeout", "value": "10" }
    - { "name": "net.core.somaxconn", "value": "4096" }
    - { "name": "net.ipv4.tcp_max_syn_backlog", "value": "8192" }
    - { "name": "net.ipv4.ip_local_port_range", "value": "10000 65000" }
  tags:
    - system-all
    - system-change-sysctl

# Adds an informative command prompt format for root user with time display and color highlighting
- name: Add custom PS1 to root's .bashrc
  lineinfile:
    path: /root/.bashrc
    line: 'PS1="[\A$(date ''+%:::z'')\[\033[35m\] \u@\h\[\033[m\]:\w]# "'
    state: present
    insertafter: EOF

# Configures automatic color highlighting for the grep command
- name: Add GREP_OPTIONS to root's .bashrc
  lineinfile:
    path: /root/.bashrc
    line: 'export GREP_OPTIONS=''--color=auto'''
    state: present
    insertafter: EOF

# Sets the highlight color for grep command (purple)
- name: Add GREP_COLOR to root's .bashrc
  lineinfile:
    path: /root/.bashrc
    line: 'export GREP_COLOR=''1;35'''
    state: present
    insertafter: EOF

# Sets high limits for open files and processes, which is important for high-load servers
- name: correct system limits
  pam_limits: domain=* limit_type=- limit_item={{ item.name }} value={{ item.value }}
  with_items:
    - { "name": "nofile", "value": "512000" }
    - { "name": "nproc", "value": "64000" }
  tags:
    - system-all
    - system-change-limits-conf

# Removes the default limits file that might override our settings
- name: Delete default 90-nproc.conf
  file:
    path: "/etc/security/limits.d/90-nproc.conf"
    state: absent
  tags:
    - system-all
    - system-change-limits-conf

# Installs a basic set of utilities and tools for system monitoring and administration
- name: install base Packages
  apt:
    name:
      - "mc"           # Midnight Commander - file manager
      - "iotop"        # I/O usage monitoring by processes
      - "iftop"        # Network traffic monitoring
      - "wget"         # Utility for downloading files
      - "deltarpm"     # Optimization for RPM package updates
      - "lsof"         # Information about open files
      - "screen"       # Terminal session manager
      - "finger"       # Information about system users
      - "mlocate"      # Fast file search
      - "ncdu"         # Disk space usage analyzer
      - "netcat"       # Network utility for working with TCP/UDP
      - "mtr"          # Network diagnostic tool
      - "tcpdump"      # Network traffic analyzer
      - "pigz"         # Parallel implementation of gzip
      - "ngrep"        # Network grep for packet monitoring
      - "net-tools"    # Classic network tools (ifconfig, netstat, etc.)
      - "ntp"
    # lock_timeout: 360
    state: present
    update_cache: yes
  ignore_errors: yes
  tags:
    - system-all
    - system-rpm
